#file: noinspection UndefinedAction,UndefinedParamsPresent
name: Build and Push ARM64 Docker Image (Angular Webview)

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd719366c4c615ad0d6819db0352d1715cc31a  # v4.2.0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@97ffb9bff4efd75940917c8125dc8ae2c56f4c7d  # v3.2.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@60773f17706dbebf33a9f9eee6251b6f1bbba60a  # v3.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@aaf152f7134c0d4ebcf358967b1a884270181c71  # v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ARM64 image
        uses: docker/build-push-action@4fe1110c69acb95ba218414c52b51624754d0eb1  # v5.1.0
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: rgee/vacuum-cleaner-view:arm64-latest
